### ISSUE TITLE
Port over IP:geo mapping code from the last secret jesus

### ISSUE THREAD

**Issue by 6peterlu** [6peterlu/secret-jesus-v2#2]
in here somewhere: https://github.com/6peterlu/plasma-xmas

**Comment by abrantigan** [comment]
did this I think? might be things missing haha

**Comment by 6peterlu** [comment]
closed https://github.com/6peterlu/secret-jesus-v2/commit/72f9d1ea6d066644e06743029a6d1a55527727c1
